// Minimal AsyncRevealVault ABI — only the methods the UI calls.
// Generated by hand to keep the bundle tiny; full typechain output lives in
// `<project>/types/contracts/AsyncRevealVault.ts` if you need it.
export const VAULT_ABI = [
  "function lock(bytes32 encAmount, bytes32 encSecret, bytes proof, uint256 revealAt) returns (uint256 vaultId)",
  "function triggerReveal(uint256 vaultId)",
  "function fulfillReveal(uint256 vaultId, bytes abiEncodedCleartexts, bytes decryptionProof)",
  "function getEncryptedAmount(uint256 vaultId) view returns (bytes32)",
  "function getEncryptedSecret(uint256 vaultId) view returns (bytes32)",
  "function getRevealAt(uint256 vaultId) view returns (uint256)",
  "function isRevealed(uint256 vaultId) view returns (bool)",
  "function getClearValues(uint256 vaultId) view returns (uint64, uint256)",
  "function nextVaultId() view returns (uint256)",
  "event Locked(uint256 indexed vaultId, address indexed depositor, uint256 revealAt)",
  "event RevealRequested(uint256 indexed vaultId)",
  "event Revealed(uint256 indexed vaultId, uint64 amount, uint256 secret)",
] as const;
